{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "2.3.9.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "h4uwaxvkonfqho4q5mr4ryupnm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.3.9.RELEASE.jar",
          "url": "spring-boot-autoconfigure-2.3.9.RELEASE.jar",
          "size": 1483303,
          "sha512": "aefa9701e64eabea28a9d72008e177dbe69901819c9046541df7fba4ed3079f5eb32dc8caf27a956dd895e2c8555752953e000e42515f5ebb5c267eb5c913dd2",
          "sha256": "b28ab329c8c2b5226f9f40af3568c77c8b19248f78503fcf8a1260d2df3c3c81",
          "sha1": "bbea8a1a7196c5194c310ed07d2d1b674aeca5f6",
          "md5": "342905966d0aa3d21398ce3a9237aea8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.3.9.RELEASE.jar",
          "url": "spring-boot-autoconfigure-2.3.9.RELEASE.jar",
          "size": 1483303,
          "sha512": "aefa9701e64eabea28a9d72008e177dbe69901819c9046541df7fba4ed3079f5eb32dc8caf27a956dd895e2c8555752953e000e42515f5ebb5c267eb5c913dd2",
          "sha256": "b28ab329c8c2b5226f9f40af3568c77c8b19248f78503fcf8a1260d2df3c3c81",
          "sha1": "bbea8a1a7196c5194c310ed07d2d1b674aeca5f6",
          "md5": "342905966d0aa3d21398ce3a9237aea8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.3.9.RELEASE-javadoc.jar",
          "url": "spring-boot-autoconfigure-2.3.9.RELEASE-javadoc.jar",
          "size": 2261053,
          "sha512": "32ee309dfc27866248ba9f7f31cc6e2bffb5d920e5cf64c1d381838d1c1178e6c745cbf576892e06ad2a35d7f235cb8fb1c84d2be04e7e2f2b10297212f28cfc",
          "sha256": "4b9b66541ff37ec5fb6177f488f0bd7a65e43506f10bfcf3e73f278a7ed0269b",
          "sha1": "e53aeeb0213f2adbd964c6125f671a785e3e787b",
          "md5": "ac34a8f76b7620914145000a042a6fa5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.3.9.RELEASE-sources.jar",
          "url": "spring-boot-autoconfigure-2.3.9.RELEASE-sources.jar",
          "size": 898196,
          "sha512": "2d1b08c9c2f8568014782ccbbeddcbce222d5166419d8e6487bf43cde4ec18f552a3aa50b8e5dc5b5b1a2824b1f0e138da4197c9258fb61871929f8cdab15578",
          "sha256": "729dd62d65566489a9ece4021a52bf5f6c2ebb6a56cc26c91c9a4a029a09a9f5",
          "sha1": "44ab8aa1f10d1b87ce91b80100ea2b94257e9282",
          "md5": "bcf14aded2e6623984f7cfb5f5293a0e"
        }
      ]
    }
  ]
}
