{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.platform",
    "module": "junit-platform-commons",
    "version": "1.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "kozkajlgabecndw6j7bo7cxnki"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.6.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-commons-1.6.3.jar",
          "url": "junit-platform-commons-1.6.3.jar",
          "size": 96679,
          "sha512": "b4b4ff143d5d3eaa76048772253b8324cb31633d7b07a9b7c312a7d0b4b9aef241625e22a36b90359b0601540c07e0cdf9d269f3bd609fd5d299a64c796da922",
          "sha256": "49be6439351fdb50f0b7827e555acad26504a8084b6bc4019b2e6d73bc9da91a",
          "sha1": "7ce526bbb9e6202e8a30140a50bfff644fddd10e",
          "md5": "9fd0e23cd3409e8698e521d6953d6a18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.6.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-commons-1.6.3.jar",
          "url": "junit-platform-commons-1.6.3.jar",
          "size": 96679,
          "sha512": "b4b4ff143d5d3eaa76048772253b8324cb31633d7b07a9b7c312a7d0b4b9aef241625e22a36b90359b0601540c07e0cdf9d269f3bd609fd5d299a64c796da922",
          "sha256": "49be6439351fdb50f0b7827e555acad26504a8084b6bc4019b2e6d73bc9da91a",
          "sha1": "7ce526bbb9e6202e8a30140a50bfff644fddd10e",
          "md5": "9fd0e23cd3409e8698e521d6953d6a18"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-commons-1.6.3-javadoc.jar",
          "url": "junit-platform-commons-1.6.3-javadoc.jar",
          "size": 618146,
          "sha512": "94ba73e8be42363517caa9683f2ac84b1896b6211e0914c015fa951a3e2c2b504e245c851baa1f24f393135e5b9604d4b64bf5354baa8a90a983a56d40119adb",
          "sha256": "68b7f10551f6e5139230cc083374850a666c7924d6f8ad67a41d08614c1cc47c",
          "sha1": "65ea865f0b7c0b05fda06619c37399d1ee32fb0f",
          "md5": "f144e316938e44c5d8f7dd95893f9e67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-commons-1.6.3-sources.jar",
          "url": "junit-platform-commons-1.6.3-sources.jar",
          "size": 70904,
          "sha512": "9a643e94ee9f152e75b6f0a6e5d8067ce09352d26e7fa26473e6ffb4ebdc09ee8d777e06340d86bdaf7ce27de10da10dfedf6a1930bb60c7d2edb14ccd6577b4",
          "sha256": "fd509a94046d28990fd7d848b0664cef62c2d995c7fee8ca5e5bd56cd41c774b",
          "sha1": "e276379850676f048f602fedbbe7d4209bf67610",
          "md5": "9b771f570a97e6c7be9b5059335ccfac"
        }
      ]
    }
  ]
}
