{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter",
    "version": "5.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "kozkajlgabecndw6j7bo7cxnki"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.6.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "5.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-5.6.3.jar",
          "url": "junit-jupiter-5.6.3.jar",
          "size": 6360,
          "sha512": "c87bf42c19ae5b539422e2e350ae3bf5b7f2bb290b92b23c4c04632bffe7acdab17473401d0aaaa0af57ff842ee814ba6085010a093098b257099e503e29f41a",
          "sha256": "380bde7098b4f6448f620afcdc2e3695896a57ee3620cfaa29ad274be1d78a61",
          "sha1": "e02aa6453c90c8fb12a88212df94d477dc97ad9b",
          "md5": "059cb9430876670317a7d012f2138f7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.6.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "5.6.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-5.6.3.jar",
          "url": "junit-jupiter-5.6.3.jar",
          "size": 6360,
          "sha512": "c87bf42c19ae5b539422e2e350ae3bf5b7f2bb290b92b23c4c04632bffe7acdab17473401d0aaaa0af57ff842ee814ba6085010a093098b257099e503e29f41a",
          "sha256": "380bde7098b4f6448f620afcdc2e3695896a57ee3620cfaa29ad274be1d78a61",
          "sha1": "e02aa6453c90c8fb12a88212df94d477dc97ad9b",
          "md5": "059cb9430876670317a7d012f2138f7f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-5.6.3-javadoc.jar",
          "url": "junit-jupiter-5.6.3-javadoc.jar",
          "size": 5681,
          "sha512": "a8ff3b71c20f40cb5c93cf183dbed22a0110e7468f8775692617a312549a78045638e428f64c3ae2efb697aa109f725be8301c9cf1c8f3ba53770337bb16fdcb",
          "sha256": "384a3aae70cf027a082a7a9989fe59ef1ae6b957001d34b090dc1bb4389816eb",
          "sha1": "dc4efd020034ec1ec2f898943e4cc07e00ac1263",
          "md5": "0603b6a33302c756853b7ce6e9e1795f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-5.6.3-sources.jar",
          "url": "junit-jupiter-5.6.3-sources.jar",
          "size": 6091,
          "sha512": "4094bfe16472632d2462d300910095278cc30e7d1ae7d373b1e82a0aa866e45459085196c1190d2b85db4b3c748c8dec9571de142f30648c85b0d0cd626ab604",
          "sha256": "44baeac391cd3da18f58d6ee3686e2bfde05519373b70edb5303ba4de58a6859",
          "sha1": "d633f276dc1d1a3ed91bb951151c7b54cbeceb96",
          "md5": "59a2aa7bdd6e6964278e9d5e681b3289"
        }
      ]
    }
  ]
}
